### ISSUE TITLE
Small misspelling in guide [part: 3, section: "Adding a route handler for /books"]

### ISSUE THREAD

**Issue by joelbrostrom** [akrabat/kitura_bookshelfapi#3]
Loved this guide and it helped me a lot.
However I thought I might as well point out a small miss, and since I'm new to GitHub in general I don't know where to put it so feel free to delete this and shout angrily at me :)

In part 3, we are supposed to create a new directory called handler, but the header showing the path says *Sources/BookshelfAPI/Handers/ListBooksHandler.swift*.
I'm guessing Handers should be Handlers.

**Comment by akrabat** [comment]
Thanks @joelbrostrom. I've updated that page.
